export enum EventStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  SOLDOUT = 'SOLDOUT',
  CANCELLED = 'CANCELLED',
  INACTIVE = 'INACTIVE',
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
}
